### ISSUE TITLE
Don't use all path scores

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/ExomiserSimulations#1]
https://github.com/monarch-initiative/ExomiserSimulations/blob/a52fe4e8ddaee8bc9ced9c2508b2d09bdd170894/plain-threes/src/main/java/org/monarchinitiative/exomiser/simulations/plain_threes/commands/SimulateCaseAndRunExomiserCommand.java#L47-L53

@ielis These won't work well - SIFT, POLYPHEN and MUTATION_TASTER do not play well with REVEL and MVP. We found REVEL + MVP **only** to be most effective. If you also want non-coding you'll need REMM and/or CADD too.

**Comment by ielis** [comment]
Okay, I'll use REVEL & MVP then. Thanks a lot!
